[package]
name = "cs444"
version = "0.1.0"
authors = ["Kevan Hollbach <khollbach@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
walkdir = "2"
